#remodel.proc.class=kr.co.weeds.process.bfp.BFPLogRemodel
#set.sessionId.from.cookie=PHPSESSIONID
#param_string.mode=N
#table.systemmap.urlcheck=Y
#mapping.opuser.by.opuserid=Y
#mapping.opuser.by.opuserid.prefix=ttt_
user.mapping.by.ip=Y
force.copy.traceId.from.parent=N
#ip.except=
#ip.unique=
#param_string.systemmap[s_dept\=*test*]=demo1new_2
#param_value.writeonly[0]=<ReportCode>REP6B345E2A964D4164B589C0B57317A9D1</ReportCode>
#param_value.writeonly[1]=test
#screen.map[params].contains.check=Y
set.clientIp.from.opuser=N